--- # Black list Working
- hosts: apacheweb
  user: ansi
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Blacklist the dummy kernel module
      kernel_blacklist: name=dummy state=absent
