--- # CRON Module
- hosts: apacheweb
  user: ansi
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Add a CRON job
      cron: name="list files 2" minute="0" hour="1" job="ls -al /etc > /home/ansi/time.log" 
