--- # File System Example
- hosts: appserver
  user: ansi
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Format the remote data partition
      filesystem: fstype=ext3 dev=/dev/xvdf1 opts='-cc'
