--- # Loop Testing
- hosts: local
  user: ansi
  become: true
  connection: ssh
  gather_facts: no
  tasks:
    - name: Add New Users 
      user: name={{ item }} state=absent
      with_items:
        - user1
        - user2
        - user3

