--- # Outline to Playbook translation
- hosts: apacheweb
  user: ansi
  become: true
  gather_facts: no
  tasks: 
  - name: check timestamp
    command: /usr/bin/date
    register: timestamp_start
  - debug: var=timestamp_start
  - name: Install something
    yum: pkg=httpd state=latest
    notify: start Httpd
  - name: verify that webservice is running
    command: systemctl status httpd
    register: result
  - debug: var=result
  - name: install client software
    yum: pkg=telnet state=latest
  - name: install client software - lynx
    yum: pkg=lynx state=latest
  - name: log all the packages installed on the system
    command: yum list installed
    register: installed_result
  - debug: var=installed_result
  - name: date/time stamp for when the playbook ends
    command: /usr/bin/date
    register: final_time
  - debug: var=final_time
  handlers:
  - name: start Httpd
    action: service name=httpd state=restarted


